package swd392.project.orbitdocsbackend.rag.entity;

import jakarta.persistence.*;
import lombok.*;
import com.pgvector.PGvector;

import java.time.Instant;

/**
 * Stores the vector embedding generated by Python RAG for a {@link DocumentChunk}.
 * Uses a shared primary key (chunk_id) — one embedding per chunk.
 *
 * <p><strong>pgvector note:</strong> The {@code embedding} column is mapped as a
 * simple {@code float[]} at the Java level. Hibernate does not natively understand
 * the {@code vector} type; the column DDL is controlled by Python RAG migrations.
 * When JPA runs in {@code create-drop} mode the column will be created as
 * {@code real[]}, which pgvector can coerce — acceptable for dev.
 * In production the Python service owns the schema and uses the proper
 * {@code vector(768)} type.</p>
 *
 * <p><strong>Ownership:</strong> Python RAG writes; Java reads only.</p>
 *
 * <p>Module: rag</p>
 */
@Entity
@Table(name = "chunk_embeddings")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ChunkEmbedding {

    /**
     * Same UUID as the parent DocumentChunk — shared primary key (1-to-1).
     */
    @Id
    @Column(name = "chunk_id", updatable = false, nullable = false)
    private java.util.UUID chunkId;

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "chunk_id")
    private DocumentChunk chunk;

    /**
     * The raw embedding vector. Dimension depends on the embedding model:
     * <ul>
     *   <li>Gemini {@code text-embedding-004} → 768 floats</li>
     *   <li>OpenAI {@code text-embedding-3-small} → 1536 floats</li>
     * </ul>
     */
    @Column(name = "embedding", columnDefinition = "vector")
    private PGvector embedding;

    /** Name of the embedding model that produced this vector. */
    @Column(name = "model_name", nullable = false, length = 100)
    private String modelName;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;
}
